### ISSUE TITLE
DEMO failing on Android FireFox 47

### ISSUE THREAD

**Issue by RichardMaher** [gauntface/simple-push-demo#69] opened 2016-07-15 03:01 UTC
The Enable Push Notifications prompt/button is never enabled.

Last one :-)

**Comment by RichardMaher** [comment] 2016-07-15 05:15
Sorry, Opera Windows returns: -

Sorry this demo requires a service worker to work and it failed to install - sorry :(

**Comment by gauntface** [comment] 2016-07-15 05:24
Will double check if the error could be better on opera but opera only
supports push on android.

**Comment by RichardMaher** [comment] 2016-07-15 07:13
Thanks Mathew. 

Happy with the Opera issue but my main gripe was with Android FireFox 47.

Cheers

**Comment by gauntface** [comment] 2016-07-16 04:59
Spent a little time looking into this.

I need to find a way to get localhost working on the device, without localhost, the ip address of my local machine is treated as insecure so I can't debug it.

Concerning as the demo works on Firefox desktop but not on mobile.

**Comment by gauntface** [comment] 2016-07-16 05:37
Turns out Firefox 47 doesn't support push. There is no PushManager in the window. I'm going to leave this open so I can stub out some tests for these scenarios. I've committed a change that should give a useful error message now.

Thanks for the bug report.

**Comment by gauntface** [comment] 2016-07-16 17:20
Also added some tests for Opera Stable - Dev for desktop on linux - all seem happy with the service worker so will have to look on a windows device to see if it's a windows only issue.

**Comment by gauntface** [comment] 2016-07-16 17:25
Unfortunately I can't repro. the opera issue. Everything seems fine on Windows 10 Surface 3.

**Comment by RichardMaher** [comment] 2016-07-17 06:39
Windows 10 Intel desktop Opera 38.0

Ooops a Problem Occurred
AbortError: Registration failed - push service not available

Strange about FF. I really just wanted to use your code (nice demo) to establish that Chrome, Samsung Browser and Opera all use GCM/Firebase as the Push Service and FF uses its own crap "autopush".

**Comment by gauntface** [comment] 2016-07-19 21:18
@RichardMaher ah got you, thats expected behaviour. Opera sadly show all the API's as available on desktop and then throw an error when you attempt to subscribe the user for push. I've raised an issue with Opera but it's a closed bug tracker so not a clue what they are doing / what they think about it.

**Comment by gauntface** [comment] 2016-07-19 21:18
But Opera on mobile uses GCM.

**Closed** 2016-09-23 22:37 UTC
